### ISSUE TITLE
Follow-up issue to resolve comments on issue #96

### ISSUE THREAD

**Issue by Chethan64** [Real-Dev-Squad/skill-tree-backend#102]
### Issue Description
The issue is to track the resolution of follow-up comments in pull request #101 
Original issue links - #95 and #96 

- Integration tests for 403 and 500 status codes - https://github.com/Real-Dev-Squad/skill-tree-backend/pull/101#discussion_r1515588082
- Need a review for the changed test function names and descriptions
- Endorsement Service not an interface:  https://github.com/Real-Dev-Squad/skill-tree-backend/pull/101?q=#discussion_r1515466510
- Uppercase for props : https://github.com/Real-Dev-Squad/skill-tree-backend/pull/101?q=#discussion_r1515471834
- Need for WebMVC file - https://github.com/Real-Dev-Squad/skill-tree-backend/pull/101?q=#discussion_r1515474077
- Not sure if this should be moved to exception folder?  https://github.com/Real-Dev-Squad/skill-tree-backend/pull/101?q=#discussion_r1515474686

### Expected Behavior
NA

### Current Behavior
NA

### Screenshots
NA

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by yesyash** [comment]
- closing this as it is no longer valid
