### ISSUE TITLE
Follow-up issue to change the endorsement search implementation

### ISSUE THREAD

**Issue by Chethan64** [Real-Dev-Squad/skill-tree-backend#103]
### Issue Description
Currently, the #95 implementation uses static dummy JSON to store and return the endorsements given the userID and skillID. Once the authentication and authorization task is completed along with schema changes (if any), the search endorsement should query the database for results. This issue is a tracker to remove the dummy JSON and change the implementation of search endorsements to query the database by giving user name and skill name.

### Expected Behavior
Search endorsements should return the results querying the database given user name and skill name

### Current Behavior
Search endorsements is returning results from the static dummy JSON added in #95 based on userID and skillID

### Screenshots
NA

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
NA

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by yesyash** [comment]
- closing this as it is no longer in the pipeline
