### ISSUE TITLE
POST Endorsement - Add check for userId using website-backend APIs

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/skill-tree-backend#120]
### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by yesyash** [comment]
- closing this as it is already taken care of in #127
