### ISSUE TITLE
write unit test for all routes

### ISSUE THREAD

**Issue by yesyash** [Real-Dev-Squad/skill-tree-backend#155]
### requirements
- setup unit testing and add unit tests for all routes in the repository.

**Comment by raj1802** [comment]
- [ ] unit tests for getAll() method
- [ ] unit tests for create() method
- [ ] unit tests for getAllRequests()  method
- [ ] Unit tests for getRequestsByStatus() method
- [ ]  Unit tests for  approveRejectSkillRequest() method
- [ ]  Unit tests for  getAllEndorsementsBySkillId method
- [ ] Unit tests for create endorsement method
- [ ] Unit tests for update endorsement method

**Comment by yesyash** [comment]
- closing this as it's a clone of #160
