### ISSUE TITLE
create a doc to to list out apis where we will need integration tests

### ISSUE THREAD

**Issue by yesyash** [Real-Dev-Squad/skill-tree-backend#157]
### Description 
- create a document to list all the APIs for which integration tests are required.

**Comment by Shyam-Vishwakarma** [comment]
I want to pick this task

**Comment by Shyam-Vishwakarma** [comment]
## skill-tree APIs

### Skills APIs:

- `GET /v1/skills` - Retrieve all skills.

- `GET /v1/skills/requests` - Retrieve all skill requests, optionally filtered by status.

- `POST /v1/skills/requests/{skillId}/action` - Approve or reject a skill request. 
AuthorizedRoles: super_user

- `POST /v1/skills` - Create a new skill.
AuthorizedRoles: super_user

- `GET /v1/skills/{id}/endorsements` - Retrieve endorsements for a specific skill by ID.

- `POST /v1/skills/{id}/endorsements` - Create a new endorsement for a specific skill.


### Endorsements APIs:

- `PATCH /v1/endorsements/{id}` - Update endorsements by endorsements id
AuthorizedRoles: user, super_user

document link: [skill-tree apis](https://docs.google.com/document/d/1oSHMzzKN_bgDVDrwe4GqbZ48EpDiKfsXDKPYjKRJHxA/edit?tab=t.0)

**Comment by Shyam-Vishwakarma** [comment]
I have listed all the currently available APIs in skill-tree in the doc. If there's anything missing or further changes required, please let me know @yesyash.
