### ISSUE TITLE
[RFC] Entities required for Skill tree

### ISSUE THREAD

**Issue by vikhyat187** [Real-Dev-Squad/skill-tree-backend#2]
**Problem statement**: We wanted to store the skill details of a user, these skills can be endorsed by other developers. An endorsement after approval from the super user gets showed on user skills. 

### List of Entities
- Skill 
- Endorsements
- EndorsersList
- Users (already exists)
- UserSkill Mapping 

### Entity relations
- User -> Skill (1 : N) [we store it in UserSkillMapping]
- Endorsement  -> skill (1 : 1) [skill Id stored as fk in endorsement table]
![Skill_tree](https://github.com/Real-Dev-Squad/skill-tree-backend/assets/34045191/60823637-2819-4182-8832-0d010936d72d)

**Comment by bhtibrewal** [comment]
### Schema Design 
Skill
 - id
 - name 
 - description

Request
- requestedBy - userId
- skillId
- createdAt
- endorsements - Endorsement[ ]
- approved

Endorsement 
 - endorseredBy userId 
 - skillId
 - type ( check skill type )
 - description
 - behavior
- createdAt

**Comment by bhtibrewal** [comment]
@vikhyat187 why would need createdAt and createdBy?

**Comment by vikhyat187** [comment]
> @vikhyat187 why would need createdAt and createdBy?

I thought this will help to understand when was this skill associated to the user and by whom. But as we have this data in Endorsement request too, we can remove I guess.

**Comment by vikhyat187** [comment]
To **work with Sql on scale** the things to keep in mind
1. Having no SPOF (Multi AZ deployment)
2. Horizontal scaling the database
3. Separating the reads from master node (using read replicas)
4. Using proper indexes on data

**Comment by vikhyat187** [comment]
{
"userId":"p6Bo61VEClhtVdwW0iGH",
"skillId":"p6Bo61VEClhtVdwW0iGH",
"currentStatus":"APPROVED",
"createdAt":epoch,
"updates":[
"prevStatus": "REJECTED",
"timestamp": epoch
]
}

**Comment by DashDeipayan** [comment]
![Skill_tree](https://github.com/Real-Dev-Squad/skill-tree-backend/assets/34045191/60823637-2819-4182-8832-0d010936d72d)

**Comment by DashDeipayan** [comment]
# Updated ER Diagram

![Untitled](https://github.com/Real-Dev-Squad/skill-tree-backend/assets/34045191/0cb13b9d-412b-4e9b-b6ff-2af0f27c41d7)

**Comment by iamitprakash** [comment]
@DashDeipayan  what about users, endrosements,user_skills table.....
