### ISSUE TITLE
Build CRUD APIs

### ISSUE THREAD

**Issue by DashDeipayan** [Real-Dev-Squad/skill-tree-backend#21]
Build all CRUD API for all entities

- [x] #46
- [ ] getEndorsement `/endorsements/{endorsementId}` - randhir
- [ ] #28 - bhavika
- [ ] getUsers `/users` 
- [ ] https://github.com/Real-Dev-Squad/skill-tree-backend/issues/29 - vikhyat
- [x] #45

**Comment by vikhyat187** [comment]
Will be sharing the ETA by 15th EOD, so will be updating the ETA post that sharing the ETA

**Comment by vikhyat187** [comment]
Was able to setup the working repo in local on 17th Oct, will be going through the comments and sharing an ETA.

**Comment by yesyash** [comment]
- closing this as the changes have been done
