### ISSUE TITLE
Resolve comments on skill tree's PR

### ISSUE THREAD

**Issue by vikhyat187** [Real-Dev-Squad/skill-tree-backend#24]
Try resolving the comments in the PR #22 

Considering their are good number of changes.

ETA : 20th Oct 
Understanding the code and changes required - 12th, 13th
Will be OOO - 14th 
Making the changes - 16th, 17th, 18th 
Test with local database 18th 
Review - 19th, 20th

**Comment by yesyash** [comment]
- closing this as it is no longer valid
