### ISSUE TITLE
Create README.md file for backend setup

### ISSUE THREAD

**Issue by vikhyat187** [Real-Dev-Squad/skill-tree-backend#25]
Create a detailed steps for running the backend of Skill tree repo in local.
This will include all the steps for 
1. Setting the database using docker
2. Generating the public and private keys for Auth
3. Connecting the database to the application

ETA - 3rd Nov morning
OOO - 30th Nov travelling
Writing documentation - 31st
Review - 1st Nov + 2nd (buffer)

**Comment by yesyash** [comment]
- closing this as the changes are already done
