### ISSUE TITLE
Schema Design

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/skill-tree-backend#3]
Skill
 - id
 - name 
 - description

Request
- requestedBy - userId
- skillId
- createdAt
- endorsements - Endorsement[ ]
- approved

Endorsement 
 - endorseredBy userId 
 - skillId
 - type ( check skill type )
 - description
 - behavior
- createdAt

UserSkillMapping
- id
- userId
- skillId
- createdAt
- createdBy

**Comment by vikhyat187** [comment]
@bhtibrewal have updated the userSkillMapping table columns please have a look
