### ISSUE TITLE
Custom exception not being returned to the user

### ISSUE THREAD

**Issue by vikhyat187** [Real-Dev-Squad/skill-tree-backend#31]
Here in this code when ever we throw an custom exception, the middleware is catching the exception and returning 401 
`Access Denied !! Full authentication is required to access this resource`

_Originally posted by @vikhyat187 in https://github.com/Real-Dev-Squad/skill-tree-backend/issues/22#issuecomment-1806799078_

**Comment by yesyash** [comment]
- closing this as it is no longer valid
