### ISSUE TITLE
Code-prettier plugin

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/skill-tree-backend#36]
We can add a code-prettier plugin to the project. It'll help keep the style guide in check across all developers. https://github.com/HubSpot/prettier-maven-plugin

## Acceptance  Criteria:

1. The codebase is formatted consistently according to the defined Prettier style.
2. The format goal successfully formats supported source code files.
3. (Optional) Automatic code formatting happens before builds or commits.

## Additional Notes:

1. The developer should consult the prettier-maven-plugin documentation for detailed configuration options.
2. Consider including a .gitignore rule to ignore any automatically generated backup files created by the plugin.

**Comment by Shaily20** [comment]
Merged and tested - https://github.com/Real-Dev-Squad/skill-tree-backend/pull/105
