### ISSUE TITLE
[BE]updateEndorsementStatus -  to APPROVE /REJECT the endorsement - super user only API

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/skill-tree-backend#45]
### Issue Description
Create a super user only API endpoint to Accept/Reject the endorsement.

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Additional Information
**Design Doc** - [Here](https://docs.google.com/document/d/1ysN2GxN3aONqf7st1xnkmrOeY-9HXjP99Yfq1t9lkTk/edit?usp=sharing)

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.* 
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by yesyash** [comment]
- closing this as the changes are already merged to develop
