### ISSUE TITLE
Adding logs on different operations performed

### ISSUE THREAD

**Issue by vikhyat187** [Real-Dev-Squad/skill-tree-backend#48]
### Issue Description

[Adding logs on different operations performed]

This ticket aims for adding logs upon different operations being performed like skills creation, user creation, skill assigned to the user.

We also need to figure out where the logs to be stored, do we store them in the existing firestore collection.
How should be the log format look like and having a structured format for all the logs.

**Comment by yesyash** [comment]
- closing this as it it no longer valid
