### ISSUE TITLE
create APIs for UserModel

### ISSUE THREAD

**Issue by vikhyat187** [Real-Dev-Squad/skill-tree-backend#50]
### Issue Description

This task aims to create the APIs for /user endpoint, write the unit tests for that and integration tests for that

Final ETA - 28th Dec (Including buffer)
API completion - 23rd Dec
Unit testing - 24th Dec
Integration test - 25th Dec
PR review + buffer - 28th Dec

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

**Comment by yesyash** [comment]
- closing this as the changes are done
