### ISSUE TITLE
Hosting Skill Tree Backend on AWS EC2

### ISSUE THREAD

**Issue by MehulKChaudhari** [Real-Dev-Squad/skill-tree-backend#82]
### Issue Description
We need to take skill tree backend in production and hosted on AWS EC2

### Expected Behavior
The Skill Tree backend should be successfully hosted on AWS EC2.

### Current Behavior
Currently, we don't have any hosted API for the skill tree. 

### Reproducibility

 - [ ] This issue is reproducible
 - [x] This issue is not reproducible

### Severity/Priority
 - [x] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by yesyash** [comment]
- done tested on production https://skills.realdevsquad.com/
