### ISSUE TITLE
Add tests to search functionality for GET /endorsements

### ISSUE THREAD

**Issue by Chethan64** [Real-Dev-Squad/skill-tree-backend#96]
### Issue Description

Add unit tests and integration tests to the search functionality (https://github.com/Real-Dev-Squad/skill-tree-backend/issues/95) for GET /endorsements by skillID or userID 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Additional Information

**Design document** - https://docs.google.com/document/d/1vGNTwzyecD93LXJ_Y1Mk7hz4Km8uFs4y6EHsA-4j1ac/edit (for the feature)

- Implementing RQL-based query parameters as part of the search on the already existing GET /endorsements endpoint
- Add unit tests and integration tests to the search functionality
- Additional information about the feature can be found at https://github.com/Real-Dev-Squad/skill-tree-backend/issues/95 and in the design document

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by yesyash** [comment]
- closing this as the implementation for /endorsements has changed slightly, I will create a new ticket for this when we implement the search feature in future
