### ISSUE TITLE
[BE] Update logic for POST endorsement API 

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/skill-tree-backend#97]
### Issue Description
Earlier the logic was to check the user information into the skill tree Database

But now as we are not storing users' data in the database we need to verify the `userId` by making an API call to website-backend 
If this API call gives us success, that means the `userId` was correct and we can go ahead and create the endorsement
after verifying the user, the creation logic doesn't need to change 

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by iamitprakash** [comment]
@bhtibrewal  can you add more details into this ticket

**Comment by yesyash** [comment]
- issue no longer valid
