### ISSUE TITLE
Update staging env for Authentication

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/skill-tree-backend#98]
### Issue Description
Adding ENV variables in the skill tree staging backend for Authentication to work

```
COOKIE_NAME: rds-session-v2-staging
RDS_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----
                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                -----END PUBLIC KEY-----"
<--- PUBLIC_KEY used in RDS staging deploy -->
```

**Comment by prakashchoudhary07** [comment]
Added EVNIRONMENT=staging key
<img width="520" alt="image" src="https://github.com/Real-Dev-Squad/skill-tree-backend/assets/34452139/6dbd3839-15a1-485f-b078-82936990c672">

**Comment by prakashchoudhary07** [comment]
Added RDS_PUBLIC_KEY
<img width="535" alt="image" src="https://github.com/Real-Dev-Squad/skill-tree-backend/assets/34452139/21012808-b516-4c00-aa41-b4689f19cf9d">
